/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError'
export { CancelablePromise, CancelError } from './core/CancelablePromise'
export { OpenAPI } from './core/OpenAPI'
export type { OpenAPIConfig } from './core/OpenAPI'

export { AcademicInfoRequest } from './models/AcademicInfoRequest'
export { AcademicInfoResponse } from './models/AcademicInfoResponse'
export type { AddInternshipCommentRequest } from './models/AddInternshipCommentRequest'
export { CoordinatorUserResponse } from './models/CoordinatorUserResponse'
export type { CreateInternshipRequest } from './models/CreateInternshipRequest'
export { CreateOpportunityRequest } from './models/CreateOpportunityRequest'
export { CreateSemesterRequest } from './models/CreateSemesterRequest'
export type { CreateTicketRequest } from './models/CreateTicketRequest'
export { CurrentWorkflowStep } from './models/CurrentWorkflowStep'
export { DecideInternshipOfferRequest } from './models/DecideInternshipOfferRequest'
export { ErrorBody } from './models/ErrorBody'
export type { ErrorField } from './models/ErrorField'
export type { ErrorResponse } from './models/ErrorResponse'
export type { HealthResponse } from './models/HealthResponse'
export { InternshipActivityResponse } from './models/InternshipActivityResponse'
export { InternshipAttachmentDownloadResponse } from './models/InternshipAttachmentDownloadResponse'
export { InternshipAttachmentResponse } from './models/InternshipAttachmentResponse'
export { InternshipListItemResponse } from './models/InternshipListItemResponse'
export type { InternshipListResponse } from './models/InternshipListResponse'
export { InternshipResponse } from './models/InternshipResponse'
export { InternshipStatus } from './models/InternshipStatus'
export type { MarkAllNotificationsReadRequest } from './models/MarkAllNotificationsReadRequest'
export type { MarkAllNotificationsReadResponse } from './models/MarkAllNotificationsReadResponse'
export type { MarkNotificationReadRequest } from './models/MarkNotificationReadRequest'
export type { NotificationListResponse } from './models/NotificationListResponse'
export { NotificationResponse } from './models/NotificationResponse'
export { OpportunityAttachmentDownloadResponse } from './models/OpportunityAttachmentDownloadResponse'
export { OpportunityAttachmentResponse } from './models/OpportunityAttachmentResponse'
export type { OpportunityListResponse } from './models/OpportunityListResponse'
export { OpportunityResponse } from './models/OpportunityResponse'
export type { PatchInternshipRequest } from './models/PatchInternshipRequest'
export type { PatchOpportunityRequest } from './models/PatchOpportunityRequest'
export type { PatchSemesterRequest } from './models/PatchSemesterRequest'
export type { PatchUserRequest } from './models/PatchUserRequest'
export type { PostTicketReplyRequest } from './models/PostTicketReplyRequest'
export type { PutSemesterSelectionRequest } from './models/PutSemesterSelectionRequest'
export { SemesterEnrolmentState } from './models/SemesterEnrolmentState'
export type { SemesterListResponse } from './models/SemesterListResponse'
export { SemesterResponse } from './models/SemesterResponse'
export type { StudentProfilePatch } from './models/StudentProfilePatch'
export { StudentProfileResponse } from './models/StudentProfileResponse'
export { StudentUserResponse } from './models/StudentUserResponse'
export type { SubmitInternshipOfferRequest } from './models/SubmitInternshipOfferRequest'
export { TicketListItemResponse } from './models/TicketListItemResponse'
export type { TicketListResponse } from './models/TicketListResponse'
export { TicketReplyResponse } from './models/TicketReplyResponse'
export { TicketResponse } from './models/TicketResponse'
export { TransitionOpportunityRequest } from './models/TransitionOpportunityRequest'
export { TransitionSemesterRequest } from './models/TransitionSemesterRequest'
export { TransitionTicketRequest } from './models/TransitionTicketRequest'
export { UserActivityFeedItemResponse } from './models/UserActivityFeedItemResponse'
export type { UserActivityFeedResponse } from './models/UserActivityFeedResponse'
export type { UserResponse } from './models/UserResponse'
export type { UserWorkflowResponse } from './models/UserWorkflowResponse'
export { VerifyOpportunityRequest } from './models/VerifyOpportunityRequest'

export { HealthService } from './services/HealthService'
export { InternshipsService } from './services/InternshipsService'
export { NotificationsService } from './services/NotificationsService'
export { OpportunitiesService } from './services/OpportunitiesService'
export { SemestersService } from './services/SemestersService'
export { TicketsService } from './services/TicketsService'
export { UsersService } from './services/UsersService'
