name: Terraform Apply (Dev)

on:
  push:
    branches: [develop]
    paths:
      - "infrastructure/**"
      - ".github/workflows/_terraform.yml"
      - ".github/workflows/terraform-apply-dev.yml"
  workflow_dispatch:

concurrency:
  group: terraform-apply-dev
  cancel-in-progress: false

jobs:
  apply:
    uses: ./.github/workflows/_terraform.yml
    with:
      action: apply
      env: dev
      state_bucket: internbot-dev-ae3a3-tf-state
      wif_provider: projects/990371971523/locations/global/workloadIdentityPools/github/providers/github-provider
      terraform_sa: terraform-ci@internbot-dev-ae3a3.iam.gserviceaccount.com
