name: Terraform Plan

on:
  pull_request:
    branches: [main, develop]
    paths:
      - "infrastructure/**"
      - ".github/workflows/_terraform.yml"
      - ".github/workflows/terraform-plan.yml"

concurrency:
  group: terraform-plan-${{ github.ref }}
  cancel-in-progress: true

jobs:
  plan-dev:
    uses: ./.github/workflows/_terraform.yml
    with:
      action: plan
      env: dev
      state_bucket: internbot-dev-ae3a3-tf-state
      wif_provider: projects/990371971523/locations/global/workloadIdentityPools/github/providers/github-provider
      terraform_sa: terraform-ci@internbot-dev-ae3a3.iam.gserviceaccount.com

  plan-prod:
    if: github.base_ref == 'main'
    uses: ./.github/workflows/_terraform.yml
    with:
      action: plan
      env: prod
      state_bucket: internbot-prod-tf-state
      wif_provider: projects/947410245672/locations/global/workloadIdentityPools/github/providers/github-provider
      terraform_sa: terraform-ci@internbot-prod.iam.gserviceaccount.com
